export const matchesJanAge = [{
    "event": {
        "_id": "642b74dcad7c9e49cf97e67f",
        "name": "January AGE Open",
        "location": "Pasadena, CA",
        "format": "Classic Constructed",
        "startDate": "2023-01-07T00:00:00.000Z",
        "endDate": null,
        "description": "https://www.age.events/pages/january-age-open ",
        "backgroundPosition": 17,
        "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670875/ofbdsnqiutuj0d5al4jb.jpg",
        "dayRoundArr": [],
        "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670873/jmzk3zbrll9sss18ptsu.jpg"
    },
    "_id": "642b7fe5ff5f3ef28bc36cac",
    "player1name": "Jacob Bertrand",
    "player1deck": "",
    "player1hero": "Fai, Rising Rebellion",
    "player2name": "Alan Chavarin",
    "player2deck": "",
    "player2hero": "Iyslander, Stormbind",
    "top8": false,
    "swissRound": 1,
    "top8Round": "None",
    "format": "Classic Constructed",
    "link": "42U0QkG3SfQ",
    "timeStamp": 0,
    "deleted": false,
    "__v": 0
},
{
    "event": {
        "_id": "642b74dcad7c9e49cf97e67f",
        "name": "January AGE Open",
        "location": "Pasadena, CA",
        "format": "Classic Constructed",
        "startDate": "2023-01-07T00:00:00.000Z",
        "endDate": null,
        "description": "https://www.age.events/pages/january-age-open ",
        "backgroundPosition": 17,
        "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670875/ofbdsnqiutuj0d5al4jb.jpg",
        "dayRoundArr": [],
        "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670873/jmzk3zbrll9sss18ptsu.jpg"
    },
    "_id": "642b8724ff5f3ef28bc36e37",
    "player1name": "Aidan Kwasneski",
    "player1deck": "",
    "player1hero": "Dash, Inventor Extraordinaire",
    "player2name": "Alejandro Cuevas",
    "player2deck": "",
    "player2hero": "Dash, Inventor Extraordinaire",
    "top8": false,
    "swissRound": 2,
    "top8Round": "None",
    "format": "Classic Constructed",
    "link": "1T_NvSQHRAk",
    "timeStamp": 0,
    "deleted": false,
    "__v": 0
},
{
    "event": {
        "_id": "642b74dcad7c9e49cf97e67f",
        "name": "January AGE Open",
        "location": "Pasadena, CA",
        "format": "Classic Constructed",
        "startDate": "2023-01-07T00:00:00.000Z",
        "endDate": null,
        "description": "https://www.age.events/pages/january-age-open ",
        "backgroundPosition": 17,
        "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670875/ofbdsnqiutuj0d5al4jb.jpg",
        "dayRoundArr": [],
        "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670873/jmzk3zbrll9sss18ptsu.jpg"
    },
    "_id": "642b87ccff5f3ef28bc36e67",
    "player1name": "Anthony Pham",
    "player1deck": "",
    "player1hero": "Iyslander, Stormbind",
    "player2name": "Andrew Goodwin",
    "player2deck": "",
    "player2hero": "Dash, Inventor Extraordinaire",
    "top8": false,
    "swissRound": 3,
    "top8Round": "None",
    "format": "Classic Constructed",
    "link": "q4r0OjqoKoQ",
    "timeStamp": 9800,
    "deleted": false,
    "__v": 0
},
{
    "event": {
        "_id": "642b74dcad7c9e49cf97e67f",
        "name": "January AGE Open",
        "location": "Pasadena, CA",
        "format": "Classic Constructed",
        "startDate": "2023-01-07T00:00:00.000Z",
        "endDate": null,
        "description": "https://www.age.events/pages/january-age-open ",
        "backgroundPosition": 17,
        "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670875/ofbdsnqiutuj0d5al4jb.jpg",
        "dayRoundArr": [],
        "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670873/jmzk3zbrll9sss18ptsu.jpg"
    },
    "_id": "642b883cff5f3ef28bc36e87",
    "player1name": "Jamaica James",
    "player1deck": "",
    "player1hero": "Bravo, Showstopper",
    "player2name": "Anthony Pham",
    "player2deck": "",
    "player2hero": "Iyslander, Stormbind",
    "top8": false,
    "swissRound": 4,
    "top8Round": "None",
    "format": "Classic Constructed",
    "link": "q4r0OjqoKoQ",
    "timeStamp": 12553,
    "deleted": false,
    "__v": 0
},
{
    "event": {
        "_id": "642b74dcad7c9e49cf97e67f",
        "name": "January AGE Open",
        "location": "Pasadena, CA",
        "format": "Classic Constructed",
        "startDate": "2023-01-07T00:00:00.000Z",
        "endDate": null,
        "description": "https://www.age.events/pages/january-age-open ",
        "backgroundPosition": 17,
        "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670875/ofbdsnqiutuj0d5al4jb.jpg",
        "dayRoundArr": [],
        "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670873/jmzk3zbrll9sss18ptsu.jpg"
    },
    "_id": "642b8899ff5f3ef28bc36ea5",
    "player1name": "Craig Pollack",
    "player1deck": "",
    "player1hero": "Oldhim, Grandfather of Eternity",
    "player2name": "Angel Benitez",
    "player2deck": "",
    "player2hero": "Briar, Warden of Thorns",
    "top8": false,
    "swissRound": 5,
    "top8Round": "None",
    "format": "Classic Constructed",
    "link": "q4r0OjqoKoQ",
    "timeStamp": 15588,
    "deleted": false,
    "__v": 0
},
{
    "event": {
        "_id": "642b74dcad7c9e49cf97e67f",
        "name": "January AGE Open",
        "location": "Pasadena, CA",
        "format": "Classic Constructed",
        "startDate": "2023-01-07T00:00:00.000Z",
        "endDate": null,
        "description": "https://www.age.events/pages/january-age-open ",
        "backgroundPosition": 17,
        "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670875/ofbdsnqiutuj0d5al4jb.jpg",
        "dayRoundArr": [],
        "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670873/jmzk3zbrll9sss18ptsu.jpg"
    },
    "_id": "642b88f0ff5f3ef28bc36ec5",
    "player1name": "Thomas Huynh",
    "player1deck": "",
    "player1hero": "Bravo, Showstopper",
    "player2name": "Travis Wagner",
    "player2deck": "",
    "player2hero": "Fai, Rising Rebellion",
    "top8": false,
    "swissRound": 6,
    "top8Round": "None",
    "format": "Classic Constructed",
    "link": "q4r0OjqoKoQ",
    "timeStamp": 18939,
    "deleted": false,
    "__v": 0
},
{
    "event": {
        "_id": "642b74dcad7c9e49cf97e67f",
        "name": "January AGE Open",
        "location": "Pasadena, CA",
        "format": "Classic Constructed",
        "startDate": "2023-01-07T00:00:00.000Z",
        "endDate": null,
        "description": "https://www.age.events/pages/january-age-open ",
        "backgroundPosition": 17,
        "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670875/ofbdsnqiutuj0d5al4jb.jpg",
        "dayRoundArr": [],
        "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670873/jmzk3zbrll9sss18ptsu.jpg"
    },
    "_id": "642b9537ff5f3ef28bc36f61",
    "player1name": "Rihanna LaGrou",
    "player1deck": "https://fabrary.net/decks/01GP9B03ZJGGJ4HE85BG0VHN13",
    "player1hero": "Briar, Warden of Thorns",
    "player2name": "Chris Iaali",
    "player2deck": "https://fabrary.net/decks/01GP99673KEAMJ878TVAW751DV",
    "player2hero": "Lexi, Livewire",
    "top8": true,
    "swissRound": null,
    "top8Round": "Quarter Finals",
    "format": "Classic Constructed",
    "link": "nGnRuZhRs-o",
    "timeStamp": 744,
    "deleted": false,
    "__v": 0
},
{
    "event": {
        "_id": "642b74dcad7c9e49cf97e67f",
        "name": "January AGE Open",
        "location": "Pasadena, CA",
        "format": "Classic Constructed",
        "startDate": "2023-01-07T00:00:00.000Z",
        "endDate": null,
        "description": "https://www.age.events/pages/january-age-open ",
        "backgroundPosition": 17,
        "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670875/ofbdsnqiutuj0d5al4jb.jpg",
        "dayRoundArr": [],
        "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670873/jmzk3zbrll9sss18ptsu.jpg"
    },
    "_id": "642b9572ff5f3ef28bc36f7f",
    "player1name": "Craig Pollack",
    "player1deck": "https://fabrary.net/decks/01GP98PX7BTCPBZNZG0D8R0BER",
    "player1hero": "Oldhim, Grandfather of Eternity",
    "player2name": "Anthony Pham",
    "player2deck": "https://fabrary.net/decks/01GP99XA085KYE6G1BQRVXF8AB",
    "player2hero": "Iyslander, Stormbind",
    "top8": true,
    "swissRound": null,
    "top8Round": "Semi Finals",
    "format": "Classic Constructed",
    "link": "nGnRuZhRs-o",
    "timeStamp": 3448,
    "deleted": false,
    "__v": 0
},
{
    "event": {
        "_id": "642b74dcad7c9e49cf97e67f",
        "name": "January AGE Open",
        "location": "Pasadena, CA",
        "format": "Classic Constructed",
        "startDate": "2023-01-07T00:00:00.000Z",
        "endDate": null,
        "description": "https://www.age.events/pages/january-age-open ",
        "backgroundPosition": 17,
        "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670875/ofbdsnqiutuj0d5al4jb.jpg",
        "dayRoundArr": [],
        "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688670873/jmzk3zbrll9sss18ptsu.jpg"
    },
    "_id": "642b95f9ff5f3ef28bc36f9b",
    "player1name": "Craig Pollack",
    "player1deck": "https://fabrary.net/decks/01GP98PX7BTCPBZNZG0D8R0BER",
    "player1hero": "Oldhim, Grandfather of Eternity",
    "player2name": "Chris Iaali",
    "player2deck": "https://fabrary.net/decks/01GP99673KEAMJ878TVAW751DV",
    "player2hero": "Lexi, Livewire",
    "top8": true,
    "swissRound": null,
    "top8Round": "Finals",
    "format": "Classic Constructed",
    "link": "nGnRuZhRs-o",
    "timeStamp": 7852,
    "deleted": false,
    "__v": 0
}]

export const matchesBaltimoreProtour = [
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451ab0b7227560bd2e65918",
        "player1name": "Michael Hamilton",
        "player1deck": "",
        "player1hero": "Lexi, Livewire",
        "player2name": "Colin Swisher",
        "player2deck": "",
        "player2hero": "Uzuri, Switchblade",
        "top8": false,
        "swissRound": 1,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "00h05m02s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451ad327227560bd2e6595d",
        "player1name": "Clark Jansen",
        "player1deck": "",
        "player1hero": "Bravo, Showstopper",
        "player2name": "Mateusz Jasinski",
        "player2deck": "",
        "player2hero": "Katsu, the Wanderer",
        "top8": false,
        "swissRound": 2,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "01h12m49s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451adb27227560bd2e65976",
        "player1name": "Adam Matecki",
        "player1deck": "",
        "player1hero": "Iyslander, Stormbind",
        "player2name": "Ethan Van Sant",
        "player2deck": "https://fabrary.net/decks/01GYJ08VJTE151PZ0JHGTY1CGN",
        "player2hero": "Rhinar, Reckless Rampage",
        "top8": false,
        "swissRound": 2,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "01h37m51s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451ae367227560bd2e6598f",
        "player1name": "Tyler Horspool",
        "player1deck": "",
        "player1hero": "Briar, Warden of Thorns",
        "player2name": "Charles Dunn",
        "player2deck": "",
        "player2hero": "Oldhim, Grandfather of Eternity",
        "top8": false,
        "swissRound": 3,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "02h15m44s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451ae8d7227560bd2e659ab",
        "player1name": "Bryce Stroyek",
        "player1deck": "",
        "player1hero": "Lexi, Livewire",
        "player2name": "TaoTao Chu",
        "player2deck": "",
        "player2hero": "Uzuri, Switchblade",
        "top8": false,
        "swissRound": 4,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "03h19m36s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451af9c7227560bd2e659c2",
        "player1name": "Alvaro Francisco Tolerado Benito",
        "player1deck": "",
        "player1hero": "Lexi, Livewire",
        "player2name": "Alan Chavarin",
        "player2deck": "https://fabrary.net/decks/01GZFH9ES79SZ822F981MR4HBM",
        "player2hero": "Levia, Shadowborn Abomination",
        "top8": false,
        "swissRound": 4,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "03h59m09s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451b2f07227560bd2e659f8",
        "player1name": "Bartosz Ziemba",
        "player1deck": "",
        "player1hero": "Uzuri",
        "player2name": "TaoTao Chu",
        "player2deck": "",
        "player2hero": "Azalea",
        "top8": false,
        "swissRound": 5,
        "top8Round": "None",
        "format": "Draft",
        "twitch": true,
        "twitchTimeStamp": "06h14m27s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451b7e17227560bd2e65a27",
        "player1name": "Paul Mirande",
        "player1deck": "",
        "player1hero": "Uzuri",
        "player2name": "TaoTao Chu",
        "player2deck": "",
        "player2hero": "Azalea",
        "top8": false,
        "swissRound": 6,
        "top8Round": "None",
        "format": "Draft",
        "twitch": true,
        "twitchTimeStamp": "07h06m37s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451b8277227560bd2e65a40",
        "player1name": "Allen Lau",
        "player1deck": "",
        "player1hero": "Arakni, Solitary Confinement",
        "player2name": "TaoTao Chu",
        "player2deck": "",
        "player2hero": "Azalea",
        "top8": false,
        "swissRound": 7,
        "top8Round": "None",
        "format": "Draft",
        "twitch": true,
        "twitchTimeStamp": "07h49m33s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451b8827227560bd2e65a57",
        "player1name": "Jamie Faulkner",
        "player1deck": "",
        "player1hero": "Uzuri",
        "player2name": "Liam Bennett",
        "player2deck": "",
        "player2hero": "Arakni, Solitary Confinement",
        "top8": false,
        "swissRound": 7,
        "top8Round": "None",
        "format": "Draft",
        "twitch": true,
        "twitchTimeStamp": "08h14m03s",
        "link": "1805764935",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451bbe67227560bd2e65a70",
        "player1name": "Allen Lau",
        "player1deck": "",
        "player1hero": "Uzuri",
        "player2name": "Liam Bennett",
        "player2deck": "",
        "player2hero": "Azalea",
        "top8": false,
        "swissRound": 8,
        "top8Round": "None",
        "format": "Draft",
        "twitch": true,
        "twitchTimeStamp": "00h14m27s",
        "link": "1806750995",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451bfff7227560bd2e65aaf",
        "player1name": "Nova Chan",
        "player1deck": "",
        "player1hero": "Uzuri",
        "player2name": "Andrew Rothermel",
        "player2deck": "",
        "player2hero": "Katsu",
        "top8": false,
        "swissRound": 10,
        "top8Round": "None",
        "format": "Draft",
        "twitch": true,
        "twitchTimeStamp": "00h13m35s",
        "link": "1806816628",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451c02a7227560bd2e65aca",
        "player1name": "Florin-Cristian Loghin",
        "player1deck": "",
        "player1hero": "Arakni, Solitary Confinement",
        "player2name": "Brodie Spurlock",
        "player2deck": "",
        "player2hero": "Katsu",
        "top8": false,
        "swissRound": 10,
        "top8Round": "None",
        "format": "Draft",
        "twitch": true,
        "twitchTimeStamp": "00h28m23s",
        "link": "1806816628",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451c2bb7227560bd2e65ae1",
        "player1name": "Mara Faris",
        "player1deck": "https://fabtcg.com/decklists/mara-faris-dromai-deck---protour-baltimore-270423/",
        "player1hero": "Dromai, Ash Artist",
        "player2name": "Florin-Cristian Loghin",
        "player2deck": "",
        "player2hero": "Lexi, Livewire",
        "top8": false,
        "swissRound": 11,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "01h06m14s",
        "link": "1806816628",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451c3957227560bd2e65af8",
        "player1name": "Matthew Foulkes",
        "player1deck": "https://fabtcg.com/decklists/matthew-foulkes-lexi-deck---protour-baltimore-270423/",
        "player1hero": "Lexi, Livewire",
        "player2name": "Ilias Karamanis",
        "player2deck": "",
        "player2hero": "Oldhim, Grandfather of Eternity",
        "top8": false,
        "swissRound": 12,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "02h06m59s",
        "link": "1806816628",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451c5277227560bd2e65b46",
        "player1name": "Francesco Giorgio",
        "player1deck": "",
        "player1hero": "Uzuri, Switchblade",
        "player2name": "Juha Saarnilampi",
        "player2deck": "https://fabtcg.com/decklists/juha-saarnilampi-dromai-deck---protour-baltimore-270423/",
        "player2hero": "Dromai, Ash Artist",
        "top8": false,
        "swissRound": 13,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "03h37m28s",
        "link": "1806816628",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451c5c17227560bd2e65b61",
        "player1name": "Ilias Karamanis",
        "player1deck": "",
        "player1hero": "Oldhim, Grandfather of Eternity",
        "player2name": "Ian Zhang",
        "player2deck": "",
        "player2hero": "Dromai, Ash Artist",
        "top8": false,
        "swissRound": 14,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "04h42m34s",
        "link": "1806816628",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451c6767227560bd2e65b89",
        "player1name": "Francesco Giorgio",
        "player1deck": "",
        "player1hero": "Uzuri, Switchblade",
        "player2name": "Michael Jaszczur",
        "player2deck": "",
        "player2hero": "Oldhim, Grandfather of Eternity",
        "top8": false,
        "swissRound": 14,
        "top8Round": "None",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "05h12m14s",
        "link": "1806816628",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451c81b7227560bd2e65ba0",
        "player1name": "Michael Feng",
        "player1deck": "https://fabtcg.com/decklists/michael-feng-oldhim-deck---protour-baltimore-270423/",
        "player1hero": "Oldhim, Grandfather of Eternity",
        "player2name": "Jake Warburton",
        "player2deck": "https://fabtcg.com/decklists/jake-warburton-azalea-deck---protour-baltimore-270423/",
        "player2hero": "Azalea, Ace in the Hole",
        "top8": true,
        "swissRound": null,
        "top8Round": "Quarter Finals",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "00h32m48s",
        "link": "1807645052",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451c8ad7227560bd2e65bbd",
        "player1name": "Andrew Rothermel",
        "player1deck": "https://fabtcg.com/decklists/andrew-rothermel-lexi-deck---protour-baltimore-270423/",
        "player1hero": "Lexi, Livewire",
        "player2name": "Maximilian Klien",
        "player2deck": "https://fabtcg.com/decklists/maximilian-klein-lexi-deck---protour-baltimore-270423/",
        "player2hero": "Lexi, Livewire",
        "top8": true,
        "swissRound": null,
        "top8Round": "Quarter Finals",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "02h06m37s",
        "link": "1807645052",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451c93b7227560bd2e65bda",
        "player1name": "Juha Saarnilampi",
        "player1deck": "https://fabtcg.com/decklists/juha-saarnilampi-dromai-deck---protour-baltimore-270423/",
        "player1hero": "Dromai, Ash Artist",
        "player2name": "Matthew Foulkes",
        "player2deck": "https://fabtcg.com/decklists/matthew-foulkes-lexi-deck---protour-baltimore-270423/",
        "player2hero": "Lexi, Livewire",
        "top8": true,
        "swissRound": null,
        "top8Round": "Quarter Finals",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "03h27m44s",
        "link": "1807645052",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451cc537227560bd2e65bf5",
        "player1name": "Brodie Spurlock",
        "player1deck": "https://fabtcg.com/decklists/brodie-spurlock-lexi-deck---protour-baltimore-270423/",
        "player1hero": "Lexi, Livewire",
        "player2name": "Mara Faris",
        "player2deck": "https://fabtcg.com/decklists/mara-faris-dromai-deck---protour-baltimore-270423/",
        "player2hero": "Dromai, Ash Artist",
        "top8": true,
        "swissRound": null,
        "top8Round": "Quarter Finals",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "04h38m38s",
        "link": "1807645052",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451ccd07227560bd2e65c15",
        "player1name": "Michael Feng",
        "player1deck": "https://fabtcg.com/decklists/michael-feng-oldhim-deck---protour-baltimore-270423/",
        "player1hero": "Oldhim, Grandfather of Eternity",
        "player2name": "Juha Saarnilampi",
        "player2deck": "https://fabtcg.com/decklists/juha-saarnilampi-dromai-deck---protour-baltimore-270423/",
        "player2hero": "Dromai, Ash Artist",
        "top8": true,
        "swissRound": null,
        "top8Round": "Semi Finals",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "05h45m56s",
        "link": "1807645052",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451cd987227560bd2e65c3c",
        "player1name": "Andrew Rothermel",
        "player1deck": "https://fabtcg.com/decklists/andrew-rothermel-lexi-deck---protour-baltimore-270423/",
        "player1hero": "Lexi, Livewire",
        "player2name": "Mara Faris",
        "player2deck": "https://fabtcg.com/decklists/mara-faris-dromai-deck---protour-baltimore-270423/",
        "player2hero": "Dromai, Ash Artist",
        "top8": true,
        "swissRound": null,
        "top8Round": "Semi Finals",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "07h55m42s",
        "link": "1807645052",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    },
    {
        "event": {
            "_id": "6451413c7227560bd2e658f3",
            "name": "Pro Tour Baltimore",
            "location": "Baltimore, MD",
            "format": "Mixed",
            "startDate": "2023-04-28T00:00:00.000Z",
            "endDate": "2023-04-30T00:00:00.000Z",
            "description": "",
            "dayRoundArr": [
                7,
                14
            ],
            "top8Day": true,
            "backgroundPosition": 24,
            "bigImage": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607558/h7pg6knuol72puiftdnw.jpg",
            "image": "https://res.cloudinary.com/dzfwflvgv/image/upload/v1688607557/qkbxldeweelsceddcoxn.jpg"
        },
        "_id": "6451cde07227560bd2e65c57",
        "player1name": "Mara Faris",
        "player1deck": "https://fabtcg.com/decklists/mara-faris-dromai-deck---protour-baltimore-270423/",
        "player1hero": "Dromai, Ash Artist",
        "player2name": "Michael Feng",
        "player2deck": "https://fabtcg.com/decklists/michael-feng-oldhim-deck---protour-baltimore-270423/",
        "player2hero": "Oldhim, Grandfather of Eternity",
        "top8": true,
        "swissRound": null,
        "top8Round": "Finals",
        "format": "Classic Constructed",
        "twitch": true,
        "twitchTimeStamp": "09h03m23s",
        "link": "1807645052",
        "timeStamp": null,
        "deleted": false,
        "__v": 0
    }
]